In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('healthcheck_colombia.csv')
print(df.shape)
df.head(10)

(350, 13)

,id_trabajador,edad,ciudad,cargo,sector,nivel,anios_experiencia,horas_semana,salario_cop,nivel_estres,dias_ausencia_anio,satisfaccion_laboral,fecha_ingreso
0,1001,28,Bogotá,QA Engineer,Fintech,Junior,1,48.0,10859922.0,2.0,10.0,6.0,01/01/2018
1,1002,41,Barranquilla,UX Designer,Consultoría,Junior,9,56.0,6190583.0,8.0,6.0,8.0,04/01/2018
2,1003,50,Barranquilla,Desarrollador Junior,E-commerce,Lead,11,50.0,4099908.0,6.0,4.0,6.0,07/01/2018
3,1004,36,Bogotá,UX Designer,Healthtech,Senior,16,46.0,4664412.0,4.0,16.0,9.0,10/01/2018
4,1005,32,Medellín,Desarrollador Junior,Healthtech,Mid,7,53.0,7809792.0,5.0,19.0,9.0,13/01/2018
5,1006,29,Bogotá,Data Analyst,Edtech,Mid,10,58.0,4853847.0,8.0,8.0,2.0,16/01/2018
6,1007,50,Barranquilla,QA Engineer,Edtech,Mid,2,43.0,5392478.0,3.0,13.0,10.0,19/01/2018
7,1008,42,Bucaramanga,DevOps,Consultoría,Junior,5,45.0,NaN,NaN,11.0,1.0,22/01/2018
8,1009,28,Bucaramanga,Product Manager,Consultoría,Lead,8,49.0,8449852.0,4.0,5.0,2.0,25/01/2018
9,1010,47,Cali,Desarrollador Junior,Fintech,Mid,5,46.0,2529725.0,1.0,16.0,5.0,28/01/2018

In [6]:
df.dtypes

id_trabajador             int64
edad                      int64
ciudad                      str
cargo                       str
sector                      str
nivel                       str
anios_experiencia         int64
horas_semana            float64
salario_cop             float64
nivel_estres            float64
dias_ausencia_anio      float64
satisfaccion_laboral    float64
fecha_ingreso               str
dtype: object

In [7]:
df.info

<bound method DataFrame.info of      id_trabajador  edad        ciudad                 cargo       sector  \
0             1001    28        Bogotá           QA Engineer      Fintech
1             1002    41  Barranquilla           UX Designer  Consultoría
2             1003    50  Barranquilla  Desarrollador Junior   E-commerce
3             1004    36        Bogotá           UX Designer   Healthtech
4             1005    32      Medellín  Desarrollador Junior   Healthtech
..             ...   ...           ...                   ...          ...
345           1346    28      Medellín           UX Designer  Consultoría
346           1347    49  Barranquilla  Desarrollador Junior      Fintech
347           1348    37      Medellín                DevOps   Healthtech
348           1349    47  Barranquilla          Data Analyst   E-commerce
349           1350    37  Barranquilla  Desarrollador Senior  Consultoría

      nivel  anios_experiencia  horas_semana  salario_cop  nivel_estres  \
0    Junior                  1          48.0   10859922.0           2.0
1    Junior                  9          56.0    6190583.0           8.0
2      Lead                 11          50.0    4099908.0           6.0
3    Senior                 16          46.0    4664412.0           4.0
4       Mid                  7          53.0    7809792.0           5.0
..      ...                ...           ...          ...           ...
345     Mid                  6          41.0    4260462.0           3.0
346  Junior                 17          54.0    6558848.0           5.0
347     Mid                  2          59.0    3309178.0           2.0
348     Mid                  9          57.0   10432310.0           NaN
349  Senior                  6          54.0    7277402.0           6.0

     dias_ausencia_anio  satisfaccion_laboral fecha_ingreso
0                  10.0                   6.0    01/01/2018
1                   6.0                   8.0    04/01/2018
2                   4.0                   6.0    07/01/2018
3                  16.0                   9.0    10/01/2018
4                  19.0                   9.0    13/01/2018
..                  ...                   ...           ...
345                10.0                   5.0    01/11/2020
346                 0.0                   2.0    04/11/2020
347                16.0                   7.0    07/11/2020
348                14.0                   4.0    10/11/2020
349                19.0                   1.0    13/11/2020

[350 rows x 13 columns]>

In [8]:
df.describe()

,id_trabajador,edad,anios_experiencia,horas_semana,salario_cop,nivel_estres,dias_ausencia_anio,satisfaccion_laboral
count,350.000000,350.000000,350.000000,350.000000,3.150000e+02,322.000000,350.000000,328.000000
mean,1175.500000,36.942857,8.705714,49.517143,7.477139e+06,5.260870,9.994286,5.347561
std,101.180532,9.229773,5.700925,6.387083,5.613608e+06,2.848231,11.024847,2.880058
min,1001.000000,22.000000,0.000000,40.000000,2.519675e+06,0.000000,0.000000,1.000000
25%,1088.250000,29.000000,4.000000,44.000000,5.008809e+06,3.000000,5.000000,3.000000
50%,1175.500000,37.000000,9.000000,49.000000,7.198713e+06,5.000000,10.000000,5.000000
75%,1262.750000,45.750000,13.000000,54.750000,9.496370e+06,8.000000,14.000000,8.000000
max,1350.000000,51.000000,54.000000,97.000000,9.500000e+07,10.000000,187.000000,10.000000

In [9]:
df.isnull().sum()

id_trabajador            0
edad                     0
ciudad                  15
cargo                    0
sector                   0
nivel                    0
anios_experiencia        0
horas_semana             0
salario_cop             35
nivel_estres            28
dias_ausencia_anio       0
satisfaccion_laboral    22
fecha_ingreso            0
dtype: int64

In [20]:
# Imputacion 1 salario ----- mediana 
mediana = df['salario_cop'].median()
df["salario_cop"].fillna(df["salario_cop"].median(), inplace=True)
df["salario_cop"].median()

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3992\464257837.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["salario_cop"].fillna(df["salario_cop"].median(), inplace=True)

np.float64(7198713.0)

In [22]:
# Imputacion  2 salario --- media

estres = df['nivel_estres'].mean()
print(f'Media del nivel de estrés: {estres}')
df['nivel_estres'] = df['nivel_estres'].fillna(estres)

Media del nivel de estrés: 5.260869565217392

In [24]:
# Imputacion  3 satisfaccion laboral --- media

estres = df['satisfaccion_laboral'].mean()
print(f'Media de la satisfacción laboral: {estres}')
df['satisfaccion_laboral'] = df['satisfaccion_laboral'].fillna(estres)

Media de la satisfacción laboral: 5.347560975609756

In [27]:

df['satisfaccion_laboral'] = df['satisfaccion_laboral'].fillna(
df['satisfaccion_laboral'].median())
print(df['satisfaccion_laboral'].median())

5.347560975609756

In [32]:
#Imputación ciudad moda
ciudad_moda = df['ciudad'].mode()[0]
print(f'Moda de la ciudad: {ciudad_moda}')
df['ciudad'] = df['ciudad'].fillna(ciudad_moda)

Moda de la ciudad: Bucaramanga

In [33]:
df.isnull().sum()

id_trabajador           0
edad                    0
ciudad                  0
cargo                   0
sector                  0
nivel                   0
anios_experiencia       0
horas_semana            0
salario_cop             0
nivel_estres            0
dias_ausencia_anio      0
satisfaccion_laboral    0
fecha_ingreso           0
dtype: int64

In [ ]:
# IQR = Q3 − Q1

# Límite inferior = Q1 − (1.5 × IQR)

# Límite superior = Q3 + (1.5 × IQR)

$$

IQR = Q3 - Q1

$$

$$

Limite\;superior = Q1 - (1.5*IQR)

$$

$$

Limite\;inferior = Q3 + (1.5*IQR)

$$

In [35]:
# Cuartiles 
Q1 = df['horas_semana'].quantile(0.25)
Q3 = df['horas_semana'].quantile(0.75)
IQR = Q3 - Q1

print(f'Q1: {Q1}')
print(f'Q3: {Q3}')
print(f'IQR: {IQR}')

Q1: 44.0
Q3: 54.75
IQR: 10.75

In [39]:
Límite_inferior = Q1 - (1.5 * IQR)

Límite_superior = Q3 + (1.5 * IQR)
print(f"Límite_inferior: {Límite_inferior:.2f} horas")

print(f"Límite_superior: {Límite_superior:.2f} horas")

Límite_inferior: 27.88 horas
Límite_superior: 70.88 horas

In [41]:
outliers_iqr = df[
(df['horas_semana'] < Límite_inferior) |
(df['horas_semana'] > Límite_superior)
]

print(f"Outliers detectados en horas_semana: {len(outliers_iqr)}")
print(outliers_iqr[['id_trabajador', 'cargo', 'nivel', 'horas_semana']])

Outliers detectados en horas_semana: 1
    id_trabajador                 cargo   nivel  horas_semana
12           1013  Desarrollador Junior  Junior          97.0

Z = (valor - media) / desviación estándar

Grupo A — Salarios: $4.9M, $5.0M, $5.1M, $5.0M, $5.0M
→ Media = $5M, Desviación estándar ≈ $0.07M (muy agrupados)

Grupo B — Salarios: $2M, $3.5M, $5M, $6.5M, $8M
→ Media = $5M, Desviación estándar ≈ $2.2M (muy dispersos)

Z= (95000000 - 5000000)/2000000 = 45