In [1]:
import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

import seaborn as sns

from sklearn.preprocessing import StandardScaler

from sklearn.cluster import KMeans

from sklearn.decomposition import PCA

import warnings

warnings.filterwarnings('ignore')

print("Librerías cargadas correctamente")

Librerías cargadas correctamente

In [2]:
df = pd.read_csv('viajaco_colombia.csv')

print(f"Dimensiones del dataset: {df.shape}")

print(f"→ {df.shape[0]} viajeros, {df.shape[1]} variables\n")

df.head()

Dimensiones del dataset: (1500, 10)
→ 1500 viajeros, 10 variables

,viajero_id,ciudad_origen,destino_preferido,tipo_viaje,canal_reserva,edad,gasto_promedio_cop,frecuencia_anual,noches_promedio,satisfaccion
0,VCO0001,Manizales,Eje Cafetero,Aventura,App móvil,18,345617,2.7,4.1,3.7
1,VCO0002,Bogotá,Medellín,Cultural,Reserva directa,46,1940263,1.2,2.2,5.0
2,VCO0003,Barranquilla,San Andrés,Descanso,Agencia tradicional,40,1309613,3.2,3.2,4.6
3,VCO0004,Barranquilla,Cartagena,Descanso,Reserva directa,33,932102,1.7,6.6,4.0
4,VCO0005,Bogotá,Santa Marta,Aventura,Recomendación,30,310989,2.0,4.3,3.0

In [3]:
print("Tipos de datos:")

print(df.dtypes)

print(f"\nValores nulos por columna:")

print(df.isnull().sum())

Tipos de datos:
viajero_id                str
ciudad_origen             str
destino_preferido         str
tipo_viaje                str
canal_reserva             str
edad                    int64
gasto_promedio_cop      int64
frecuencia_anual      float64
noches_promedio       float64
satisfaccion          float64
dtype: object

Valores nulos por columna:
viajero_id            0
ciudad_origen         0
destino_preferido     0
tipo_viaje            0
canal_reserva         0
edad                  0
gasto_promedio_cop    0
frecuencia_anual      0
noches_promedio       0
satisfaccion          0
dtype: int64

In [4]:
df.describe().round(2)

,edad,gasto_promedio_cop,frecuencia_anual,noches_promedio,satisfaccion
count,1500.00,1500.00,1500.00,1500.00,1500.00
mean,34.35,1189147.06,2.88,4.38,4.33
std,8.82,860673.49,1.55,1.51,0.45
min,18.00,150000.00,1.00,1.00,2.50
25%,27.00,381947.50,1.70,3.30,4.00
50%,34.00,1088448.00,2.40,4.20,4.40
75%,41.00,1751357.00,4.00,5.40,4.70
max,60.00,3310726.00,7.80,10.00,5.00

In [5]:
variables_numericas = ['edad', 'gasto_promedio_cop', 'frecuencia_anual',

'noches_promedio', 'satisfaccion']

X = df[variables_numericas].copy()

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

print(f"Shape de X_scaled: {X_scaled.shape}")

print(f"\nMedia por columna después del escalado (debe ser ≈ 0):")

print(X_scaled.mean(axis=0).round(4))

print(f"\nDesviación estándar por columna después del escalado (debe ser ≈ 1):")

print(X_scaled.std(axis=0).round(4))

Shape de X_scaled: (1500, 5)

Media por columna después del escalado (debe ser ≈ 0):
[-0.  0. -0. -0.  0.]

Desviación estándar por columna después del escalado (debe ser ≈ 1):
[1. 1. 1. 1. 1.]